version: "3.7"

services:
  ui:
    build: 
      context: ./
      dockerfile: ./APP.UI/server.Dockerfile
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
    driver: local
